### ISSUE TITLE
Handle block devices and network interfaces

### ISSUE THREAD

**Issue by baurma** [antoniopuero/open-m-monit#4]
Hello,

Please find a unified diff attached that will enable open-m-monit to handle block devices and network interfaces.

Cheers,
  Marcel

patch -p0 < diff.txt
[diff.txt](https://github.com/antoniopuero/open-m-monit/files/304236/diff.txt)

**Comment by antoniopuero** [comment]
Hi,

thanks for your pull request :) I've updated the repo.

Could you please youse github pull request feature next time? it's much easier to use
